src/Entity/Ad.php
<?php

namespace App\Entity;

use App\Entity\User;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdRepository")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 *  fields={"title"},
 *  message="Une annonce porte déjà ce titre, vous devriez en changer ;-)"
 * )
 */
class Ad
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $coverImage;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="ads")
     */
    private $owner;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="ad", cascade={"persist"}, orphanRemoval=true)
     */
    private $images;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="ad", orphanRemoval=true)
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function generateSlug(){
        if(empty($this->slug)){
            $slugifier = new Slugify();
            $this->slug = $slugifier->slugify($this->title);
        }
    }

    public function getCommentFromAuthor(User $user) {
        foreach($this->comments as $comment) {
            if($comment->getAuthor() === $user) return $comment;
        }
        return null;
    }

    public function getAvgRatings(){
        $sum = array_reduce($this->comments->toArray(), function($total, $comment){
            return $total + $comment->getRating();
        }, 0);

        if(count($this->comments)) return $sum / count($this->comments);

        return 0;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug = null): self
    {
        $this->slug = $slug ? $slug : '';
        
        if(empty($this->slug)) {
            $slugifier = new Slugify();
            $this->slug = $slugifier->slugify($this->title);
        }

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(?string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }
    
    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * Permet de récupérer toutes les journées non disponibles pour cette annonce
     * @return array
     */
    public function getNotAvailableDays() {
        $notAvailableDays = [];
        // Pour chaque réservation
        foreach($this->bookings as $booking) {
            $dateStart  = $booking->getStartDate()->format('Y-m-d');
            $dateEnd    = $booking->getEndDate()->format('Y-m-d');
            // On calcule l'intervale en jours (86400 millisecondes)
            $range  = range(strtotime($dateStart), strtotime($dateEnd), 86400);
            
            $days   = array_map(function($day) {
                return new \DateTime(date('Y-m-d', $day));
            }, $range);

            $notAvailableDays = array_merge($notAvailableDays, $days);
        }

        return $notAvailableDays;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }
}

templates/partials/ad.html.twig
<div class="col-md-4">
    <div class="card bg-light mb-3">
        <div class="card-header text-center">
            {{ad.rooms}} chambres, <strong>{{ad.price|number_format(2,',', ' ')}}&euro; / nuit</strong> <br>
            {% if ad.comments|length > 0 %}
                {% set rating = ad.avgRatings %}
                {% include 'partials/rating.html.twig' %}
            {% else %}
                <small>Pas encore noté</small>
            {% endif %}
        </div>
        
        <a href="{{ path('ads_show', {slug: ad.slug}) }}">
            <img style="height: 200px; width: 100%; display: block;" src="{{ad.coverImage}}" alt="Image de l'annonce {{ad.title}}">
        </a>

        <div class="card-body">
            <h4 class="card-title">
                <a href="{{ path('ads_show', {slug: ad.slug}) }}">
                    {{ ad.title }}
                </a>
            </h4>
            <p class="card-text">{{ad.introduction}}</p>
            <a href="{{ path('ads_show', {slug: ad.slug}) }}" class="btn btn-primary float-right">En savoir plus !</a>
            {% if app.user and app.user == ad.owner %}
                <a href="{{ path('ads_edit', {slug: ad.slug}) }}" class="btn btn-secondary">Modifier l'annonce</a>
            {% endif %}
        </div>
    </div>
</div>

templates/partials/header.html.twig
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{{ path('home') }}">SymBnB !</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if app.request.attributes.get('_route') == 'home' %}active{% endif %}">
        <a class="nav-link" href="{{ path('home') }}">Home</a>
      </li>
      <li class="nav-item {% if app.request.attributes.get('_route') == 'ads_index' %}active{% endif %}">
        <a class="nav-link" href="{{ path('ads_index') }}">Annonces</a>
      </li>
    </ul>
    <ul class="navbar-nav my-2 my-lg-0">
      {% if app.user %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <img src="{{app.user.picture}}" class="avatar avatar-mini mr-1" alt=""> {{app.user.firstName}} {{app.user.lastName}}
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{{path("ads_create")}}">Créer une annonce</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{{path("account_index")}}">Mon compte</a>
          <a class="dropdown-item" href="{{path("account_bookings")}}">Mes réservations</a>
          <a class="dropdown-item" href="{{path("account_profile")}}">Modifier mon profile</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{{path("account_logout")}}">Déconnexion</a>
        </div>
      </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{{ path('account_login') }}">Connexion</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>

{% for label, messages in app.flashes %}
  <div class="container">
      <div class="alert alert-{{label}} alert-dismissible">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {% for message in messages %}
            <p>
                {{ message | raw }}
            </p>
        {% endfor %}
      </div>
  </div>
{% endfor %}

templates/partials/pagination.html.twig
{% set routeParams = routeParams|default({})|merge(app.request.query.all) %}
{% set route = route|default(app.request.attributes.get('_route')) %}
<div class="d-flex justify-content-center mt-2">
    <ul class="pagination">
        <li class="page-item {% if page == 1 %} disabled {% endif %}">
            <a class="page-link" href="{{path(route, routeParams|merge({'page': page - 1}))}}">&laquo;</a>
        </li>
        {% for i in 1..pages %}
            <li class="page-item {% if i == page %} active {% endif %}">
                <a class="page-link" href="{{ path(route, routeParams|merge({'page': i})) }}">{{i}}</a>
            </li>
        {% endfor %}
        <li class="page-item {% if page == pages %} disabled {% endif %}">
            <a class="page-link" href="{{path(route, routeParams|merge({'page': page + 1}))}}">&raquo;</a>
        </li>
    </ul>
</div>

templates/partials/rating.html.twig
<span class="rating">
    {% for i in 1..5 %}
        {% if i <= rating %}
            <i class="fas fa-star"></i>
        {% else %}
            <i class="far fa-star"></i>
        {% endif %}
    {% endfor %}
</span>

templates/partials/sort.html.twig
{% if headerData is defined %}
<div class="alert alert-light rounded">
    <form method="get">
        <div class="form-group">
            <div class="row align-items-center">
                <div class="col-md-6">
                    <h1 class="alert-heading">{{headerData.title}}</h1>
                </div>
                {% if headerData.sortFields is defined and headerData.directions is defined %}
                <div class="col-md-1">
                    <label for="sort">Trier par :</label>
                </div>
                <div class="col-md-3">
                    <select name="sort" id="sort" class="form-control" onchange="this.form.submit()">
                        {% for field, title in headerData.sortFields %}
                            <option value="{{field}}" {% if headerData.sort == field %}selected{% endif %}>{{title}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-md-2">
                    <select name="direction" id="direction" class="form-control" onchange="this.form.submit()">
                        {% for order,title in headerData.directions %}
                            <option value="{{order}}" {% if headerData.direction == order %}selected{% endif %}>{{title}}</option>
                        {% endfor %}
                    </select>      
                </div>
                {% endif %}
            </div>
        </div>
    </form>
</div>
{% endif %}